name: iamrick
description: I Am Rick.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Courier-Prime
      fonts:
        - asset: fonts/Courier-Prime.ttf
    - family: Courier-Prime-Bold
      fonts:
        - asset: fonts/Courier-Prime-Bold.ttf